DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS User;

CREATE TABLE "Message" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Text"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);

CREATE TABLE "User" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Login"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL UNIQUE,
	"Salt"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
)